#
# Event types for CIM alignment and reusable searches.
#

[darkmoon_finding]
search = sourcetype=darkmoon:finding

[darkmoon_campaign]
search = sourcetype=darkmoon:campaign

[darkmoon_pr]
search = sourcetype=darkmoon:pr

[darkmoon_retest]
search = sourcetype=darkmoon:retest
